version: "3"

services:
  api-estrategia:
    build:
        context: .
        dockerfile: ./build/Dockerfile
    image: api-estrategia
    env_file:
      - .env
    container_name: api-estrategia
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    expose:
      - 3000
    extra_hosts:
      - "host.docker.internal:host-gateway"